### ISSUE TITLE
Screenshot/explaination of plugin interface

### ISSUE THREAD

**Issue by jacksongoode** [ni/plotly-panel#1]
We are currently using https://github.com/ae3e/ae3e-plotly-panel but it looks like it will not be maintained. Just wondering how this plugin interfaces with Plotly?

**Comment by mure** [comment]
Hi @jacksongoode
This plugin was designed for internal use foremost, so no public documentation has been created yet. That being said, we're open to outside collaboration! I recorded a short GIF to give you an idea of the plugin's capabilities:

![Kapture 2022-07-13 at 15 09 47](https://user-images.githubusercontent.com/9257800/178827423-a83ab245-6034-4f24-8849-7b1bacbb93d2.gif)
